# Generated by Django 4.2.7 on 2023-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('image_origin', models.CharField(max_length=255)),
                ('image_detect', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
