# Generated by Django 4.2.7 on 2023-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_fixed',
            field=models.CharField(default='', max_length=255),
        ),
    ]
