# Generated by Django 4.2.7 on 2023-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_vehicle_file_name_vehicle_license_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='folder_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
